### ISSUE TITLE
final review, and release 1.0

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/php-vips#14]
I think everything has now been ticked off the TODO list, we can probably release 1.0.

How about making a 0.1.2 release with what's in dev, and then leaving it for few weeks. If it seems to be working with no major issues, we'll bump again to 1.0. Use this issue to track minor polishing on the way.

**Comment by jcupitt** [comment]
TODO

- [ ] remove the `Enum` subdirectory, it introduces too much noise
- [ ] make sure everything passes phpcs PSR2, note the `--standard` setting we use in README

**Comment by kleisauke** [comment]
- Should Travis CI also run the PHPUnit tests? Because that requires to make the `php-vips-ext` work with Travis CI. Maybe checking for syntax errors should be good for now.
- Which fields should be included in the `__toString()` function? I think this would give use the basic info about an image:
```php
    /**
     * Makes a string-ified version of the Image.
     *
     * @return string
     */
    public function __toString()
    {
        $array = [
            'width' => $this->get('width'),
            'height' => $this->get('height'),
            'bands' => $this->get('bands'),
            'format' => $this->get('format'),
            'interpretation' => $this->get('interpretation'),
        ];

        return json_encode($array);
    }
```

**Comment by jcupitt** [comment]
Yes, we should check `php-vips-ext` in travis too. It shouldn't be too hard, I hope.

**Comment by jcupitt** [comment]
I'll have a look at the php 7.1 issue next.

**Comment by jcupitt** [comment]
Yes, your `_toString()` looks good!

**Comment by kleisauke** [comment]
For the `gh-pages`:
- We could auto-generate API docs with [ApiGen](https://github.com/ApiGen/ApiGen) (used by the [CakePHP Framework](http://api.cakephp.org/3.0/) and [Doctrine ORM API](http://www.doctrine-project.org/api/orm/2.4/)) or [Sami](https://github.com/FriendsOfPHP/Sami) (used by the [Symfony API](http://api.symfony.com/)). Not sure which one we should choose, because I haven't used any API docs generator in the past. I'll take a look to both generators at the weekend to see which one fits best to our needs. (I'm not sure how the `docs` directory is generated now)
- We can use Travis CI to auto-generate our docs every time we push a commit to master. See [here](https://gist.github.com/domenic/ec8b0fc8ab45f39403dd) for a example.

**Comment by koenpunt** [comment]
> Rename Vips\Main ... perhaps Vips\Vips? Vips\Utils?

What I meant is 2 classes, `Vips\Config`, which is now `Vips\Main`, but then without the `debug` & `error` functions, and `Vips\Utils`, with the `debug` and `error` method.

**Comment by jcupitt** [comment]
It's using phpdoc at the moment, so just:

```
$ vendor/bin/phpdoc
```

Perhaps there's something better.

**Comment by kleisauke** [comment]
I agree with @koenpunt. The `setLogger` and `getLogger` functions doesn't belong in the `Config` class.

I've found a better alternative, see this proof of concept here: https://gist.github.com/kleisauke/80eb1a5133b927f512041563c2d67246

This enables us to use `Vips\Base::setLogger`.

**Comment by koenpunt** [comment]
I don't think we should be using traits for this use case,  because it makes things more complicated than they should. We don't need a static method on all classes that extend from base to set the logger IMO. Also having both `Logger` and `Logging` can lead to confusion. If we add the static `debugLog` and `errorLog` functions to the `Logger` class, we _don't_ have to add an additional class and/or trait (for which I suggested `Utils` before).

**Comment by kleisauke** [comment]
Thanks for checking. 

I agree, the proof of concept that I linked make things overcomplicated. And traits are only used to duplicate code in other classes that share the same functionality (which are we not doing currently).

Made a more simpler version named `Utils`  (just what you described) _without_ using a trait and base class that we can extend. See here:
https://gist.github.com/kleisauke/1e814140351f3c9f1ada2521778e5b97

I'm not sure if we should it name it `Utils` or `Logger` because now it contains only a generic logger function.

**Comment by koenpunt** [comment]
Looks more like it, but `getLogger` and `setLogger` are configuration options, so they should be in the Config class, not in the `Logger` class.

**Comment by koenpunt** [comment]
And the `Utils` class with only 2 function is kinda maybe weird, but I'm sure there will be more functions along the way that can be added to `Utils` as well.

**Comment by jcupitt** [comment]
I think my instinct is that all the config functions and the logging stuff are "top level". If php allowed functions outside classes, we'd just have:

```php
Vips\setConcurrency(12);
Vips\setLogger(new Vips\DebugLogger);
$image = Vips\Image::newFromFile(...);
```

The singleton `Utils`, or `Main` or `Vips` or `Config` classes are only there because we can't have package globals, not because they have any real meaning. We just need a generic catch-all name to mean global package functions, and we can put the few things vips does globally (there aren't many) in there. 

Of course I'm not familiar with php conventions and we should do whatever you recommend.

**Comment by jcupitt** [comment]
Here's another solution (I think). I found this composer feature:

https://getcomposer.org/doc/04-schema.md#files

We could add this to our `composer.json`:

```
    "autoload": {
        "psr-4": {
            "Jcupitt\\Vips\\": "src"
        },
        "files": ["src/_Vips.php"]
    },
```

And now `_Vips.php` will be added to the autoload list for vips classes. We can put all of our globals in there and just refer to them as `Vips\setConcurrency(12);` or whatever.

**Comment by koenpunt** [comment]
I know about autoloading files, but I don't know if it's the right thing to do. At least I have never seen the combination of `psr` and `files` autoloading..

**Comment by jcupitt** [comment]
.... back on this again.

I renamed `error()` as errorLog()` and `debug()` as `debugLog()`, and moved them into a new `Utils` class. I think that ticks that one off.

I'll have a look at making a tiny gh-pages site to host the docs.

git master libvips now has a `thumbnail` operation which might be useful for you. Docs here:

https://github.com/jcupitt/libvips/blob/master/libvips/resample/thumbnail.c#L647

Use from php as:

```
$image = Vips\Image::thumbnail($filename, $output_width);
$image->writeToFile($output_filename);
```

There's `Image::thumbnail_buffer()` as well.

**Comment by jcupitt** [comment]
github likes to have the `docs/` directory in master, so I think we need to bump dev to 1.0 and merge to master before this can happen.

Do you think we're all ready for 1.0? I can't think of any other issues. If I get a thumbs up, I'll bump and merge.

**Comment by koenpunt** [comment]
> I renamed error() as errorLog() and debug() as debugLog(), and moved them into a new Utils class. I think that ticks that one off.

On the `dev` branch the log methods are also still in the `Config` class

**Comment by jcupitt** [comment]
Ooop, I always forget that, sorry. Fixed!

Anything else?

**Comment by koenpunt** [comment]
If you open a PR from dev to master, I can add comments in context (if necessary).
And there's one common thing; I don't think the generated docs should be in the repo,  because it causes quite some noise on the diffs.
If people clone the project and they want to read the docs they can generate them.
Isn't there a hosted service like readthedocs.org for php documentation?

**Comment by jcupitt** [comment]
I agree, the formatted docs are a pain, I've removed them. I'd hoped they wouldn't be too noisy, but phpdoc seems to make huge changes for even the smallest edit to a source file. I'll look at other ways of providing this.

Here's a PR for 1.0.0:

https://github.com/jcupitt/php-vips/pull/20

Thanks!

**Comment by koenpunt** [comment]
As an alternative we could store the generated docs in the `gh-pages` branch.

**Comment by jcupitt** [comment]
Yes, that's what I'm planning: a `gh-pages` branch with the docs and a little jekyll for an index.html.

I made a homebrew formula for the extension:

https://github.com/jcupitt/homebrew-php/tree/add-php70-vips-ext

When we get to 1.0 I'll open a PR to get that into homebrew, then you can install with just `brew install php70-vips-ext` and it'll do everything automatically, including libvips.

**Comment by kleisauke** [comment]
I think 1.0.0 is ready for releasing. Added a few inline comments in #20.

Some ideas/features for the next release, or any further release:
- Publish `php-vips-ext` in the PECL directory, so we can just use `pecl install vips` (not sure how difficult this would be; applying for a PECL account can be done [here](https://pecl.php.net/account-request.php)).
- Finish the [TODO-list](https://github.com/jcupitt/php-vips/issues/14#issuecomment-255529500). (Travis CI, `gh-pages` docs, small site).
- Windows support for `php-vips-ext`.
- Implement the `offsetSet` and `offsetUnset` methods. See #3.

**Comment by jcupitt** [comment]
I've found a blocking bug :( #21 argh.

**Comment by jcupitt** [comment]
OK, done! I'll open new issues for Travis and gh-pages and we can do them in a bit.

**Comment by koenpunt** [comment]
Did you intentionally create 2 tags? Because there's now a `v1.0.0` and a `1.0.0`. I'd believe the `v` prefixed way is more common.

**Comment by jcupitt** [comment]
Yes, I couldn't get composer to see the v version, so I did an unprefixed one as well.

**Comment by koenpunt** [comment]
> I couldn't get composer to see the v version

That sounds weird. Mayor PHP libraries (e.g. [Laravel](https://github.com/laravel/laravel/releases)) uses a v prefix.

**Comment by jcupitt** [comment]
I may just have been hasty. Perhaps you have to wait a few minutes after pushing a tag before it shows up on packageist.
