### ISSUE TITLE
Image for AWS Instance Recommendation

### ISSUE THREAD

**Issue by maxrottersman** [jcupitt/php-vips#19]
I spent a few days trying to get another image server working on AWS Linux so apologies if I'm a bit gun-shy ;) 

We use VIPs for digitiler.com  (THANKS!).   In Windows we create a DZI image repository then FTP it up to our server.  There are often over 12,000 images, so it's time-consuming.  I'd rather upload a JPG, then have VIPs do it's thing on the server, then 10 minutes later we could point to that image store and be done.

Can anyone recommend an "image"/instance on AWS that would be the quickest to set up php-vips with?  I don't want to compile anything, like PHP7, if I can help it.  Thanks again!

**Comment by jcupitt** [comment]
Hi @maxrottersman,

`php-vips` is still rather raw. We're just about to bump the version to 1.0.0 and declare it ready for use, but the current version is still 0.1.2. I think you'd be the second person to try it in production. 

Are you running `dzsave` on the client, then uploading a huge pile of tiles? A simple way to speed this up is to make a zip directly. You can write:

```
$ vips dzsave hugefile.tif mypyramid.zip
```

And vips will directly write a zip file containing all the tiles. It's much, much faster to upload. On Windows, it also makes the tiling process a lot quicker, since Windows really hates huge directories with lots of small files in.

There's a thread on the libvips tracker about lambda installs:

https://github.com/jcupitt/libvips/issues/492

It might help.

**Comment by maxrottersman** [comment]
Yes, that's what we do, create the zip first.  One of my earlier thoughts was just to de-compress the zip on the server.  Somehow I forgot about that option.  I'll work on that and report back.  Thanks!

**Comment by jcupitt** [comment]
I think this is done. Please reopen if not.
