### ISSUE TITLE
set up Travis

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/php-vips#22]
CI and badges would be nice.

**Comment by kleisauke** [comment]
These Travis CI configuration files can be useful:
https://github.com/h2non/bimg/blob/master/.travis.yml
https://github.com/Seldaek/monolog/blob/master/.travis.yml

Maybe we should wait for [php-vips-ext#1](https://github.com/jcupitt/php-vips-ext/issues/1) because that will make the installation process for Travis CI easier.

**Comment by jcupitt** [comment]
We have a PECL package!

https://pecl.php.net/package/vips

**Comment by kleisauke** [comment]
Pull request for Travis CI has been made : #25

**Comment by jcupitt** [comment]
OK, all done, I think.
