### ISSUE TITLE
composer should declare the vips extension dependency

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/php-vips#7]
We don't declare the dependency on the vips extension in `composer.json`. 

If you add the line:

```
        , "ext-vips" : ">=0.1.0"
```

to `requires:` composer fails with the error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-vips >=0.1.0 is missing from your system. Install or enable PHP's vips extension.
```

Even though `vips.so` is installed and enabled (all the `phpunit` tests pass).

**Comment by kleisauke** [comment]
If I add `"ext-vips": ">=0.1.1"` in the composer `require` block then it's working properly. (it's not throwing any errors).

If I change it for example to `"ext-vips": ">=0.2.0"` (a version number that doesn't exits) then it's throwing a error:
```bash
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-vips >=0.2.0 has the wrong version (0.1.1) installed. Install or enable PHP's vips extension.
```

So that works. 

Are you sure that composer is executed with the same PHP that has the `extension=vips.so` in the `php.ini`? You can try to run `php -m` for a list of compiled modules and check if it's in there. If not you could check the location of `php.ini` with `php -i` (on the top of the output it should tell where the ini file is loaded from) and then add  `extension=vips.so` to that ini file.

**Comment by jcupitt** [comment]
I was doing `composer install` and having problems. I hadn't realized that the system composer on Ubuntu always runs the system php, it doesn't pick up any local phps from the path. If I do `php composer.phar install`, it's all fine.

I'll close.
