### ISSUE TITLE
thumbnail class not found error

### ISSUE THREAD

**Issue by akwatra** [jcupitt/php-vips#74]
$image = Vips\Image::thumbnail('/home/me/Pictures/actress/IMG_585005.png', 128);
$image->writeToFile('./images/tiny.jpg');

PHP Fatal error:  Uncaught Jcupitt\Vips\Exception: VipsOperation: class "thumbnail" not found
 in /www/htdocs/rnd/vips/vendor/jcupitt/vips/src/Image.php:664
Stack trace:

**Comment by jcupitt** [comment]
Hello @akwatra,

Your libvips is probably too old -- `thumbnail` was added in 8.5. 

Do you know what version you are using?

**Comment by akwatra** [comment]
I also think so, as ubuntu 16.04 added as libvips42 using cli also ask for libvips-tools to install. 
I have remove that old version. also tried to make from latest build..

but not able to run from cli, and on vipsthumbnail again ask to  install  libvips-tools ... 

suggestion: if you can create and maintain ppa repository for ubuntu would easy for ubuntu community,
earlier whole day spent into glib2.6 and other deps 

it was one of most time taking and hard to install .. still not get working complete

**Comment by jcupitt** [comment]
To make your own build, remove all the libvips stuff from Ubuntu and build from source. You don't need to build any other packages or install anything strange, the latest libvips will build fine against the Ubuntu 16.04 dependencies. Install to `/usr/local` and make sure `PATH` is set correctly and `ld.so.conf` includes `/usr/local/lib`.

I'm not able to offer a PPA unfortunately. libvips users are on at least five different linuxes and I can't build for all of them :( 

I've been using Docker recently -- that might be a simple solution for you. I have a set of Dockerfiles:

https://github.com/jcupitt/docker-builds

There's one there that makes a latest php-vips stack for Ubuntu 16.04. It should be easy to adapt. It installs to `/usr`, which you'll need to change, but otherwise it should just work.
